### PR TITLE
Fix inplace fold_abbrs option call.

### PR DESCRIPTION
**Pull request by kdeldycke**

### CODE REVIEW

**Comment by dimka665** [comment]
Thanks

**Comment by kdeldycke** [comment]
Thanks to you for the fast merge !

Any plan for a awesome-slugify 1.6.5 release no PyPi ?

**Comment by dimka665** [comment]
Done

2015-06-05 9:24 GMT+03:00 Kevin Deldycke <notifications@github.com>:

**Comment by kdeldycke** [comment]
Fantastic ! :tada:

**Pull request merged**
